services:
  db:
    image: postgres
    restart: unless-stopped
    shm_size: 128mb
    networks:
      - unibook
    environment:
      POSTGRES_PASSWORD: # database password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s
  unibook:
    image: unibook
    restart: unless-stopped
    networks:
      - unibook
    ports:
      - 3000:3000
    environment:
      - MINIO_ENDPOINT=$MINIO_ENDPOINT # minio instance endpoint
      - MINIO_PORT=$MINIO_PORT # minio instance port
      - MINIO_ACCESS_KEY=$MINIO_ACCESS_KEY # minio access key
      - MINIO_SECRET_KEY=$MINIO_SECRET_KEY # minio secret key
      - MINIO_USESSL=true # use https/http to connect to minio (true or false)
      - CRYPTO_PSW=$CRYPTO_PSW # password for encryption
      - CRYPTO_SALT=$CRYPTO_SALT # salt for encryption
      - JWT_SECRET=$JWT_SECRET # secret for JsonWebTokens
      - JWT_AUDIENCE=$JWT_AUDIENCE # jwt audience (your domain)
      - JWT_ISSUER=$JWT_ISSUER # jwt issuer (your domain)
      - DB_HOST=db # database host (es. db)
      - DB_PORT=5432 # database port (es. 5432)
      - DB_DATABASE=postgres # database name (es. postgres)
      - DB_USER=postgres # database username (es. postgres)
      - DB_PASSWORD=$DB_PASSWORD # database password
    depends_on:
      db:
        condition: service_healthy
        restart: true

networks:
  unibook: